### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by ethanperrine** [zanellia/prometeo#30]
Hey, after reading a little bit about this project, I love it but I'm a little confused one a few parts; does it transpile to exe? Or what does it transpile the python code to so users can run? Also; would I have to write my python programs in such a way so prometeo is able to access and execute it? 

TY.

**Comment by zanellia** [comment]
Hey @ethanperrine, thanks for the interest in the project! prometeo transpiles Python code to C code that is then compiled into an executable and run. And yes, in order to make the transpiled code very efficient and free of memory allocation, I had to impose some extra constraints, i.e., only programs written with a specific structure and using a subset of the Python language can be transpiled. It's similar in a way to mypyc, in the sense that you have to use type hints, but on top of that you need to satisfy other constraints too (programs transpiled with mypyc still call the Python runtime library though, which can be inefficient).

**Comment by ethanperrine** [comment]
Question, would I be able to obfuscate the exe using themida/code virtualizer?

**Comment by zanellia** [comment]
I am not familiar with Themida, but what you get out of prometeo's transpilation process is a standalone C code program, so I'd say yes (I guess you want to obfuscate the source code, not the exe). I'd love to spend more time on prometeo and improve it, but at the moment is mostly on hold - if any cool application/collaboration comes up I'd be happy to put more energy into it though.
